[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = [
    "yarn prisma generate",
    "yarn prisma migrate deploy",
    "yarn build"
]

[start]
cmd = "yarn start"

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
