[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
    "npx prisma generate",
    "npx prisma migrate deploy",
    "npm run build"
]

[start]
cmd = "npm start"

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
